In [23]:
import pandas as pd

In [24]:
results_df = pd.read_csv("data/opt_lr_wd.csv")

In [9]:
results_df.columns.str.contains("adamw")  # Check for unnamed columns

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [37]:
results_df.columns[results_df.columns.str.endswith("test")]

Index(['voices_detection_optim_name='adamw'_lr=0.1_weight_decay=0.1 - epoch_f1score/test',
       'voices_detection_optim_name='adamw'_lr=0.1_weight_decay=0.01 - epoch_f1score/test',
       'voices_detection_optim_name='adamw'_lr=0.1_weight_decay=0.0 - epoch_f1score/test',
       'voices_detection_optim_name='adamw'_lr=0.05_weight_decay=0.1 - epoch_f1score/test',
       'voices_detection_optim_name='adamw'_lr=0.05_weight_decay=0.01 - epoch_f1score/test',
       'voices_detection_optim_name='adamw'_lr=0.05_weight_decay=0.0 - epoch_f1score/test',
       'voices_detection_optim_name='adamw'_lr=0.01_weight_decay=0.1 - epoch_f1score/test',
       'voices_detection_optim_name='adamw'_lr=0.01_weight_decay=0.01 - epoch_f1score/test',
       'voices_detection_optim_name='adamw'_lr=0.01_weight_decay=0.0 - epoch_f1score/test',
       'voices_detection_optim_name='adamw'_lr=0.005_weight_decay=0.1 - epoch_f1score/test',
       'voices_detection_optim_name='adamw'_lr=0.005_weight_decay=0.01 - epoch_

In [60]:
flat_f1 = results_df.iloc[:, results_df.columns.str.endswith("test")].max()

In [ ]:
flat_f1

pandas.core.series.Series

In [79]:
flat_f1_adamw = flat_f1[flat_f1.index.str.contains("adamw")]
flat_f1_sgd = flat_f1[flat_f1.index.str.contains("sgd")]

In [84]:
flat_f1_sgd.index

Index(['voices_detection_optim_name='sgd'_lr=0.1_weight_decay=0.1 - epoch_f1score/test',
       'voices_detection_optim_name='sgd'_lr=0.1_weight_decay=0.01 - epoch_f1score/test',
       'voices_detection_optim_name='sgd'_lr=0.1_weight_decay=0.0 - epoch_f1score/test',
       'voices_detection_optim_name='sgd'_lr=0.05_weight_decay=0.1 - epoch_f1score/test',
       'voices_detection_optim_name='sgd'_lr=0.05_weight_decay=0.01 - epoch_f1score/test',
       'voices_detection_optim_name='sgd'_lr=0.05_weight_decay=0.0 - epoch_f1score/test',
       'voices_detection_optim_name='sgd'_lr=0.01_weight_decay=0.1 - epoch_f1score/test',
       'voices_detection_optim_name='sgd'_lr=0.01_weight_decay=0.01 - epoch_f1score/test',
       'voices_detection_optim_name='sgd'_lr=0.01_weight_decay=0.0 - epoch_f1score/test',
       'voices_detection_optim_name='sgd'_lr=0.005_weight_decay=0.1 - epoch_f1score/test',
       'voices_detection_optim_name='sgd'_lr=0.005_weight_decay=0.01 - epoch_f1score/test',
       

In [ ]:
flat_f1_adamw.sort_values(asce

voices_detection_optim_name='adamw'_lr=0.005_weight_decay=0.1 - epoch_f1score/test     0.97744
voices_detection_optim_name='adamw'_lr=0.01_weight_decay=0.1 - epoch_f1score/test      0.97120
voices_detection_optim_name='adamw'_lr=0.01_weight_decay=0.01 - epoch_f1score/test     0.95541
voices_detection_optim_name='adamw'_lr=0.01_weight_decay=0.0 - epoch_f1score/test      0.95484
voices_detection_optim_name='adamw'_lr=0.005_weight_decay=0.0 - epoch_f1score/test     0.95233
voices_detection_optim_name='adamw'_lr=0.005_weight_decay=0.01 - epoch_f1score/test    0.95000
voices_detection_optim_name='adamw'_lr=0.05_weight_decay=0.0 - epoch_f1score/test      0.94633
voices_detection_optim_name='adamw'_lr=0.1_weight_decay=0.1 - epoch_f1score/test       0.20533
voices_detection_optim_name='adamw'_lr=0.1_weight_decay=0.01 - epoch_f1score/test      0.20533
voices_detection_optim_name='adamw'_lr=0.1_weight_decay=0.0 - epoch_f1score/test       0.20533
voices_detection_optim_name='adamw'_lr=0.05_weight

In [85]:
flat_f1_sgd

voices_detection_optim_name='sgd'_lr=0.1_weight_decay=0.1 - epoch_f1score/test       0.94421
voices_detection_optim_name='sgd'_lr=0.1_weight_decay=0.01 - epoch_f1score/test      0.98089
voices_detection_optim_name='sgd'_lr=0.1_weight_decay=0.0 - epoch_f1score/test       0.94595
voices_detection_optim_name='sgd'_lr=0.05_weight_decay=0.1 - epoch_f1score/test      0.95163
voices_detection_optim_name='sgd'_lr=0.05_weight_decay=0.01 - epoch_f1score/test     0.96250
voices_detection_optim_name='sgd'_lr=0.05_weight_decay=0.0 - epoch_f1score/test      0.95425
voices_detection_optim_name='sgd'_lr=0.01_weight_decay=0.1 - epoch_f1score/test      0.96203
voices_detection_optim_name='sgd'_lr=0.01_weight_decay=0.01 - epoch_f1score/test     0.96855
voices_detection_optim_name='sgd'_lr=0.01_weight_decay=0.0 - epoch_f1score/test      0.95172
voices_detection_optim_name='sgd'_lr=0.005_weight_decay=0.1 - epoch_f1score/test     0.96203
voices_detection_optim_name='sgd'_lr=0.005_weight_decay=0.01 - epoch_f

In [ ]:
flat_f1_adamw.values.reshape(4,3)

lr = [5e-3, 1e-2, 5e-2, 1e-1]
wd = [0.0, 1e-2, 1e-1]

array([[0.20533, 0.20533, 0.20533],
       [0.20533, 0.20533, 0.94633],
       [0.9712 , 0.95541, 0.95484],
       [0.97744, 0.95   , 0.95233]])

In [48]:
import pandas as pd
import re
PATTERN = re.compile(
    r'(?P<opt>\w+)_lr(?P<lr>[0-9.]+)_wd(?P<wd>[0-9.]+)', re.I
)

meta = (
    pd.DataFrame(df.columns)
      .rename(columns={0: "col"})
      .assign(**df.columns.to_series().str.extract(PATTERN))
      .astype({"lr": "float", "wd": "float"})
)



In [49]:
def build_matrix(opt_name: str) -> pd.DataFrame:
    # 4 a –– filtrujemy kolumny konkretnego optymalizatora
    m = meta.query("opt == @opt_name")

    # 4 b –– przygotowujemy pustą ramkę z osiami lr × wd
    lr_vals = sorted(m["lr"].unique())
    wd_vals = sorted(m["wd"].unique())
    mat = pd.DataFrame(index=lr_vals, columns=wd_vals, dtype=float)

    # 4 c –– wypełniamy komórki odpowiednimi wartościami
    for _, row in m.iterrows():
        col = row["col"]
        mat.at[row["lr"], row["wd"]] = df[col].values  # zakładamy 1 wiersz;
                                                       # w przeciwnym razie np. .mean()
    return mat


In [50]:
optimizers = meta["opt"].unique()        # np. ['adam', 'sgd']
matrices = {opt: build_matrix(opt) for opt in optimizers}

matrix_adam = matrices["adamw"]
matrix_sgd  = matrices["sgd"]


KeyError: 'adamw'

In [51]:
matrices

{nan: Empty DataFrame
 Columns: []
 Index: []}

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# --- PRZYKŁADOWA MACIERZ (symuluje Twoje wyniki) ---
learning_rates = [1e-4, 1e-3, 1e-2, 1e-1]
weight_decays  = [0.0, 1e-5, 1e-4, 1e-3]

# losowe dane tylko do demonstracji
rng = np.random.default_rng(seed=42)
vals = rng.random((len(learning_rates), len(weight_decays)))

matrix = pd.DataFrame(vals, index=learning_rates, columns=weight_decays)

# --- WIZUALIZACJA ---
plt.figure(figsize=(6, 5))
im = plt.imshow(matrix.values, aspect='auto')  # domyślny colormap
plt.colorbar(im, label="wynik")                # legenda kolorów

# opisy osi
plt.xticks(ticks=range(len(weight_decays)), labels=weight_decays)
plt.yticks(ticks=range(len(learning_rates)), labels=learning_rates)
plt.xlabel("weight decay")
plt.ylabel("learning rate")
plt.title("Przykładowa macierz wyników")

plt.tight_layout()
plt.show()


In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# --- PRZYKŁADOWA MACIERZ (symuluje Twoje wyniki) ---
learning_rates = [1e-4, 1e-3, 1e-2, 1e-1]
weight_decays  = [0.0, 1e-5, 1e-4, 1e-3]

# losowe dane tylko do demonstracji
rng = np.random.default_rng(seed=42)
vals = rng.random((len(learning_rates), len(weight_decays)))

In [71]:
vals

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499],
       [0.64386512, 0.82276161, 0.4434142 , 0.22723872]])